Update building_data.xml
StoDevX/stomap pull request #2
Opened 2017-10-15 03:17 UTC by RobertBerger5

finished all of them (not sure how useful some of the sites are for them though)

2017-10-15 03:40 UTC, hawkrives requested changes
The only one I'm going to pick on is Forest Inn. 

It's great to see students looking through this archive of stuff!

2017-10-15 03:40 UTC, hawkrives commented on building_data.xml
> +		<url>https://wp.stolaf.edu/naturallands/woodlands/</url>
http://map.stolaf.edu/map/accessible.php?id=294&cId=14889&mId=136436 ?

2017-10-16 02:47 UTC, drewvolz approved these changes

2017-10-16 02:50 UTC, hawkrives approved these changes
@RobertBerger5 I had @drewvolz fix the forest inn link and I'm merging it now

2017-10-16 02:50 UTC, merged